import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Job Application Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar />
        {children}
        <Toaster />
        <footer className="py-6 pt-10">
          <div className="container mx-auto px-4 text-center">
            <p className="text-sm font-medium">Job Application Tracker</p>
            <p className="text-xs text-muted-foreground mt-1">Built with Next.js, MongoDB, Better Auth, and AI Powered cover letter generation</p>
          </div>
        </footer>
      </body>
    </html>
  );
}
